# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fcac3e07f1a2eb04e707bef111b66471df875142bdb0c52f263d78cc718c1e39af5e8c04b1bcbd98a9ce1367435ad6633450eefde1d340c2fcd6b1d1fb3eda1

test:
  secret_key_base: 83b26333e95d5d13a68e9eaa174168f3174dabf03e4f08aa6be8f9239bee47d5044b85d07fb4199f6bc188f3c4dd1aa042c3c1bd6cc37aa9f6b92c4da338ae38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
